import type { Metadata } from "next";
import {Cabin} from "next/font/google"

const cabin = Cabin({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cabin.className}
      >
        {children}
      </body>
    </html>
  );
}
