import type { Metadata } from "next";
import {Cabin} from "next/font/google"
import { UserProvider } from "../context/UserContext";

const cabin = Cabin({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cabin.className}
      >
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
